[Settings]
  ID = "Yc54628b6-fb39-42f4-bcb3-3f738ca945f9"

[build]
  base    = "site"
  publish = "site/public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.40.3"

[context.deploy-preview]
  command = "hugo -D"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.40.3"