baseurl             = "/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = ""
author              = "Jiv Dhaliwal"
title               = "Jiv Dhaliwal"